[theme]
primaryColor = "#4F46E5"          # Indigo accent
backgroundColor = "#FFFFFF"       # White background
secondaryBackgroundColor = "#F3F4F6" # Light gray sidebar / widgets
textColor = "#111827"             # Dark gray text
font = "sans serif"
